variable "ami_type" {}
variable "instance_types" {}
variable "capacity_type" {}
variable "disk_size" {}
variable "eks_version" {}
variable "subnet_private_ids" {}
variable "subnet_public_ids" {}
variable "aws_vpc_id" {}
variable "flask_name" {}